### ISSUE TITLE
没有报错，但是显示不出来实验结果

### ISSUE THREAD

**Issue by guanzy2012** [datamllab/LongLM#15]
#Tokens of Prompt: 5144 Passkey target: 89427
This is a friendly reminder - the current text generation call will exceed the model's predefined maximum length (4096). Depending on the model, you may observe exceptions, performance degradation, or nothing at all.
Llama2:     [What is the pass key? The pass key is 。。。. 。]
SelfExtend: [What is the pass key? The pass key is 。。。. 。]

**Comment by guanzy2012** [comment]
the version of transformers is not 4.32.0

**Comment by Mooler0410** [comment]
Could you please elaborate more on your environment and your running scripts? It seems that both in our and other folks' tests, the current codes work well.

**Comment by hahmad2008** [comment]
@Mooler0410  @guanzy2012  what is the meaning of `Passkey target: 89427`? How to know the extended context length?
