### ISSUE TITLE
Example for phi2?

### ISSUE THREAD

**Issue by JoanZhou** [datamllab/LongLM#22]
Could you please release the example script for Phi-2? Thanks.

**Comment by Mooler0410** [comment]
It's similar to llama or mistral / llama. Just use  the function modify_method_of_instance (in modify_utils.py) to replace the forward method of Phi-2's attention to self-extend.

**Comment by JoanZhou** [comment]
Thank you for reply. I did so and I got answer like this:
![image](https://github.com/datamllab/LongLM/assets/20510491/212b0573-5c6d-457d-99ff-43265d69a29a)

**Comment by Mooler0410** [comment]
Thanks for the feedback! 

As we commented on the patch for phi-2 on 4.37 

"# transfromers version 4.37 (a furture version)
# Should work for 'microsoft/phi-2', a offical hf version of microsfot/phi-2, check the detail in Huggingface Hub. 
# It's dfferent from the previous version for 'susnato/phi-2', which is the default version in transformers 4.36.2 !
# Haven't done comprehensive test, but it should work."

 It may have some bugs. Will check it once I'm back from the spring break.

**Comment by Mooler0410** [comment]
> Thank you for the reply. I am using phi_self_extend_patch_4_37.py in transformers 4.37.1, and I got answer like this: ![image](https://private-user-images.githubusercontent.com/20510491/311109874-212b0573-5c6d-457d-99ff-43265d69a29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTk3MTMsIm5iZiI6MTcxMTI5OTQxMywicGF0aCI6Ii8yMDUxMDQ5MS8zMTExMDk4NzQtMjEyYjA1NzMtNWM2ZC00NTdkLTk5ZmYtNDMyNjVkNjlhMjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE2NTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzN2ZhZTZmNTNiNjM2MGY5NjJlMTM5ZDIyYTdhYjFkZjExZWUyZDU4MjMwNDdkMjE5MmU5M2JmNjI4NzY5YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDB9FFTDuG_b7N7MAzjiX1NvdJB4IKAtVM33MZDWSlU) Tried a few parameters: group_size_1=4, group_size_2=1024 group_size_1=4, group_size_2=512

Hi, we found that Phi-2 it-self cannot do passkey retrieval well 🤣. Without SelfExtend, you may try to ask the vanilla Phi-2 to do a 1.5k passkey retrieval and it will fail like the example you provided. 

**SelfExtend just elicits a LLM's long capabilities and does not equip it with any new capability. This means, if the model cannot finish a task well within its own pretraining window, it cannot do it on longer contexts with SelfExtend.** 

With the existing patch for Phi-2, on other tasks, such as 'Needle in the haystack', SelfExtend works well. Have a try!

**Comment by Mooler0410** [comment]
> Thank you for the reply. I am using phi_self_extend_patch_4_37.py in transformers 4.37.1, and I got answer like this: ![image](https://private-user-images.githubusercontent.com/20510491/311109874-212b0573-5c6d-457d-99ff-43265d69a29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzk5NTIsIm5iZiI6MTcxMjE3OTY1MiwicGF0aCI6Ii8yMDUxMDQ5MS8zMTExMDk4NzQtMjEyYjA1NzMtNWM2ZC00NTdkLTk5ZmYtNDMyNjVkNjlhMjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDIxMjczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NjZiOWEzYmIxZmZiNTc3YjQxMGFmMjE1N2NmNWMxZjJhOTg2MGFhMmY4ZWY5YjY0YjNlODE0MTEyMTNjMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SydmDjIie1NC35H_oSLgWr9QZd9UtXA91yUNtmOZHaM) Tried a few parameters: group_size_1=4, group_size_2=1024 group_size_1=4, group_size_2=512

Hi,  I happened to test Phi-2 with 4.36.2 today. It seems that Phi-2 itself can do passkey with this version, while it cannot with transformers == 4.38.2. You may consider this.

**Comment by Mooler0410** [comment]
> > Thank you for the reply. I am using phi_self_extend_patch_4_37.py in transformers 4.37.1, and I got answer like this: ![image](https://private-user-images.githubusercontent.com/20510491/311109874-212b0573-5c6d-457d-99ff-43265d69a29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzk5NTIsIm5iZiI6MTcxMjE3OTY1MiwicGF0aCI6Ii8yMDUxMDQ5MS8zMTExMDk4NzQtMjEyYjA1NzMtNWM2ZC00NTdkLTk5ZmYtNDMyNjVkNjlhMjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDIxMjczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NjZiOWEzYmIxZmZiNTc3YjQxMGFmMjE1N2NmNWMxZjJhOTg2MGFhMmY4ZWY5YjY0YjNlODE0MTEyMTNjMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SydmDjIie1NC35H_oSLgWr9QZd9UtXA91yUNtmOZHaM) Tried a few parameters: group_size_1=4, group_size_2=1024 group_size_1=4, group_size_2=512
> 
> Hi, I happened to test Phi-2 with 4.36.2 today. It seems that Phi-2 itself can do passkey with this version, while it cannot with transformers == 4.38.2. You may consider this.

This conclusion is misleading. It is one of the variants I tested works well with transformers==4.36.2. 

I tested more variants of Phi-2, find that:  with transformers==4.38.2, rhysjones/phi-2-orange-v2 works well, while "microsoft/phi-2" cannot work... It's super wired, considering that passkey retrieval is very simple. 

All the tested models are vanilla (without SelfExtend). All the input sequences have a length of 1.5k, which is within its context window (2k).

**Comment by Mooler0410** [comment]
> Thank you for the reply. I am using phi_self_extend_patch_4_37.py in transformers 4.37.1, and I got answer like this: ![image](https://private-user-images.githubusercontent.com/20510491/311109874-212b0573-5c6d-457d-99ff-43265d69a29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDU2ODQsIm5iZiI6MTcxMjIwNTM4NCwicGF0aCI6Ii8yMDUxMDQ5MS8zMTExMDk4NzQtMjEyYjA1NzMtNWM2ZC00NTdkLTk5ZmYtNDMyNjVkNjlhMjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA0MzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNmZhMDA5NTRhZTkzNmE2YTViZjk1YzY2MjU4NGIyNzI5ZmZmZTY4N2JhMjkyNmYwNDg0NmFiMzMzYzYwMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LF6ubPPCe8WaUeFOjxH_FkQ9vq8PoosrImT7-TpxufQ) Tried a few parameters: group_size_1=4, group_size_2=1024 group_size_1=4, group_size_2=512

I believe this response will be the last one. I have figured out what happens. Phi-2 is sensitive to the prompt format. Different from other models, Phi-2 requires using the recommended template: "To encourage the model to write more concise answers, you can also try the following QA format using "Instruct: <prompt>\nOutput:"(https://huggingface.co/microsoft/phi-2). With this template, now, with transfromers==4.38.2, Phi-2 can successfully do passkey retrieval.

**Comment by hahmad2008** [comment]
@Mooler0410 @JoanZhou what is the meaning of `Passkey target:`? How to know the extended context length?
